# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: canary.warp-drive.io deployment

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - labeled
      - synchronize
      - ready_for_review

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  # Determine if we should deploy
  # We deploy if
  # - this is a push to the main branch
  # - this is a pull request to the main branch and has the label `pr-preview`
  # - this was manually triggered
  checkShouldDeploy:
    runs-on: ubuntu-latest
    outputs:
      shouldDeploy: ${{ steps.shouldDeploy.outputs.shouldDeploy }}
    steps:
      - name: Check if we should deploy
        id: shouldDeploy
        run: |
          echo "shouldDeploy=true" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "This is a push to the main branch. Deploying."
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.event.action }}" == "labeled" && "${{ github.event.label.name }}" == "pr-preview" ]]; then
              echo "This is a pull request with the pr-preview label. Deploying."
            else
              echo "This is a pull request without the pr-preview label. Not deploying."
              echo "shouldDeploy=false" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "This was manually triggered. Deploying."
          else
            echo "This is not a push to the main branch or a pull request with the pr-preview label. Not deploying."
            echo "shouldDeploy=false" >> $GITHUB_OUTPUT
          fi

  # Build job
  build:
    if: ${{ needs.checkShouldDeploy.outputs.shouldDeploy == 'true' }}
    needs: checkShouldDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1 # 0 is needed if lastUpdated is enabled
      - uses: ./.github/actions/setup
        with:
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG == 'true' }}
          DISABLE_TURBO_CACHE: ${{ secrets.ACTIONS_RUNNER_DEBUG == 'true' }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Generate Artifact
        run: pnpm run build
        working-directory: docs-viewer
        env:
          BASE: '/data/'
          HOSTNAME: 'https://emberjs.github.io/data'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-viewer/docs.warp-drive.io/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
